const apiData = {
  "login": "W-Mills",
  "id": 37784155,
  "node_id": "MDQ6VXNlcjM3Nzg0MTU1",
  "avatar_url": "https://avatars3.githubusercontent.com/u/37784155?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/W-Mills",
  "html_url": "https://github.com/W-Mills",
  "followers_url": "https://api.github.com/users/W-Mills/followers",
  "following_url": "https://api.github.com/users/W-Mills/following{/other_user}",
  "gists_url": "https://api.github.com/users/W-Mills/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/W-Mills/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/W-Mills/subscriptions",
  "organizations_url": "https://api.github.com/users/W-Mills/orgs",
  "repos_url": "https://api.github.com/users/W-Mills/repos",
  "events_url": "https://api.github.com/users/W-Mills/events{/privacy}",
  "received_events_url": "https://api.github.com/users/W-Mills/received_events",
  "type": "User",
  "site_admin": false,
  "name": "William Mills",
  "company": null,
  "blog": "",
  "location": "Toronto, Canada",
  "email": null,
  "hireable": null,
  "bio": "Software Engineer",
  "public_repos": 10,
  "public_gists": 15,
  "followers": 5,
  "following": 0,
  "created_at": "2018-03-25T23:34:46Z",
  "updated_at": "2019-12-01T21:17:09Z"
}
console.log('4e755adb-758d-42b7-9eb2-aba0515243c5');
console.log(apiData);
